Enhancement ari faviconlogo
COSC481W-2022Winter/capstone-hackmcx pull request #28
Opened 2022-02-20 21:58 UTC by ahassani93

I replaced the fav-icon with the logo. Please approve! Issue #18

2022-02-20 21:59 UTC, ckhorra1 commented
Looks great!

2022-02-20 22:00 UTC, ckhorra1 approved these changes
Looks great, thank you!

2022-02-21 16:39 UTC, zxkevin requested changes
react-router-dom not part of the package and is not included when running npm ci / npm install

2022-02-21 16:39 UTC, zxkevin commented on packages/hackmcx-api/dev.env
> +DB_PASS=
Don't push any dev.env changes. This should be for you locally.

2022-02-21 16:39 UTC, zxkevin commented on packages/package-lock.json
> +{
Is this file suppose to be here? I see a copy of this already in the client folder.

2022-02-21 16:39 UTC, zxkevin commented on packages/hackmcx-client/src/LandingPage.js
> +
Please remove clutter

2022-02-21 17:22 UTC, zxkevin requested changes
Please check comments

2022-02-21 17:22 UTC, zxkevin commented on packages/hackmcx-client/src/LandingPage.js
> +			.get('http://localhost:3003/api/vi/posts')
http://localhost:3003/api/v1/posts

2022-02-21 17:22 UTC, zxkevin commented on packages/hackmcx-client/src/LandingPage.js
> +				setExample(response.data[0].CURRENT_TIMESTAMP);
response.data[0].CURRENT_TIMESTAMP will not get anything

Try:
response.data[0].imageUrl

2022-02-21 17:22 UTC, zxkevin commented on packages/hackmcx-client/src/LandingPage.js
> +			<h2>This is our Landing Page!</h2>
This will be hidden under the menu bar. Please fix display location

2022-02-21 17:22 UTC, zxkevin commented on packages/hackmcx-client/src/App.js
> +				<LandingPage />
<LandingPage /> is call twice here, I'm guessing delete the one not in <Routes>

2022-02-21 23:29 UTC, closed without merging