feat: Add password & PUT endpoint to Users
COSC481W-2022Winter/capstone-hackmcx pull request #90
Opened 2022-03-29 23:03 UTC by zxkevin

Added new migrations to update Users table with password column
Seed file added to update pre-existing seeds with a password.
POST endpoint for Users now requires a password.
PUT endpoint for {userID} added for update users functionality.
Bcrypt is used to salt and hash password for secure password storage.

#87 #51

2022-03-29 23:12 UTC, zxkevin commented on packages/hackmcx-api/src/db/seeds/2022-03-29_1757_update_demo_users.cjs
> +    return knex('users').update('password', '$2a$12$A0HScvmVMgyRKcy/BYm/tuYi7IetjaYNpzU/gVHBmtHu3EtWUPshq');
"password123"

2022-03-30 01:23 UTC, 3dxp requested changes

2022-03-30 01:23 UTC, 3dxp commented on packages/hackmcx-api/src/controllers/users.controller.js
>      const emptyUsername = !req.body.username || /^\s*$/.test(req.body.username);
I think at this point, checking for null or whitespace should be a helper function, with the regex compiled.

2022-03-30 01:23 UTC, 3dxp commented on packages/hackmcx-api/src/controllers/users.controller.js
>      if(emptyUsername){
I think these validation checks can be factored out, and maybe applied elsewhere. 

Eventually we might want to look at just adding some reasonable exception handling and breaking all this validation out of the controller.

2022-03-30 01:23 UTC, 3dxp commented on packages/hackmcx-api/src/controllers/users.controller.js
> +    const hashPass = await bcrypt.hash(req.body.password, 12);
Why is this a `const`?

2022-03-30 01:26 UTC, 3dxp commented on packages/hackmcx-api/package.json
> +    "cors": "^2.8.5",
It seems like the only thing changing here is the addition of bcrypt. We might want to consider removing the other changes, even it they do reorganize the imports in alphabetical order.

2022-03-30 16:32 UTC, acampb65 requested changes
I think preexisting seeds need to be modified. The update demo users seed works fine if rows already exist, but when running seed data on empty database MySQL gets mad:
```
code: 'ER_NO_DEFAULT_FOR_FIELD',
    errno: 1364,
    sqlState: 'HY000',
    sqlMessage: "Field 'password' doesn't have a default value",
    sql: "insert into `users` (`first_name`, `imageUrl`, `last_name`, `username`) values ('first_name1', 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/MJd1-.svg/100px-MJd1-.svg.png', 'last_name1', 'username1'), ('first_name2', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/MJd2v1-.svg/100px-MJd2v1-.svg.png', 'last_name2', 'username2'), ('first_name3', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/MJd3e-.svg/100px-MJd3e-.svg.png', 'last_name3', 'username3')"
```

2022-03-30 18:13 UTC, acampb65 commented
PUT user responds with 201 even if username doesn't exist.

example:
```
curl -X PUT -i http://localhost:3003/api/v1/users/nonExistentUsername \
-H 'Content-Type: application/json' \
-d '{"username":"user","password":"pass","firstname":"first","lastname":"last"}'
       
HTTP/1.1 201 Created
X-Powered-By: Express
Access-Control-Allow-Origin: *
Location: /api/v1/users/undefined
Date: Wed, 30 Mar 2022 18:11:43 GMT
Connection: keep-alive
Keep-Alive: timeout=5
Content-Length: 0

```

2022-03-30 21:53 UTC, 3dxp approved these changes

2022-03-30 22:06 UTC, acampb65 approved these changes
LGTM

2022-03-30 22:14 UTC, merged